on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Append Path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          # ensure bin directory
          mkdir -p "$HOME/.local/bin"
          
          # install arduino-cli into "$HOME/.local/bin"
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/.local/bin" sh
          
          # prepare config
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          
          # install
          make install
          
          # link library
          mkdir -p ~/Arduino/libraries
          ln -s $PWD ~/Arduino/libraries/.
          
          # build examples
          make build
